from . import amplitude_config
from . import amplitude_client
from . import ir_http
from . import res_users
from . import customer_rfq
from . import custom_sale_order
from . import sale_order
from . import stock_picking
from . import purchase_order
from . import res_partner
