{
    "name": "Contacts Stage Bar",
    "version": "18.0.1.7.1602",
    "sequence": -100,
    "category": "Contacts",
    "summary": "Add status bar stages to Contacts form and Kanban views",
    "description": "This module adds a status bar (pipeline stages) to Contacts form and Kanban views for easier contact status management.",
    "author": "Anirath",
    "website": "https://www.augmont.com/",
    "depends": [
        "base", "contacts", "crm", "sale", "product", "stock", "web", "purchase",
        "account", "mass_mailing", "hr", "hr_attendance", "hr_holidays", "l10n_in","spreadsheet_sale_management",
    ],
    "data": [
        'security/res_groups.xml',
        'data/res_partner_data.xml',
        'data/customer_rfq_sequence.xml',
        # 'data/customer_onboarding_sequence.xml',
        'data/customer_rfq_shape_data.xml',
        'data/customer_rfq_cancel_reason_data.xml',
        'data/customer_rfq_grade_data.xml',
        'security/ir.model.access.csv',
        'security/sale_visibility_rules.xml',
        "views/reports_label.xml",
        "views/contacts_stage_views.xml",
        "views/crm_lead.xml",
        "views/res_partner_stage.xml",
        "views/res_partner_category_views.xml",
        "views/sale_order.xml",
        "views/sale_order_add_product_wizard.xml",
        "views/sale_order_cancel_wizards.xml",
        "views/product_template_views.xml",
        "views/stock_picking_wizard_view.xml",
        "views/pay_confirm_wizard_views.xml",
	    "views/stock_picking.xml",
        "views/lgd_inventory_menu.xml",
        "views/menu_rename.xml",
        "views/res_users_views.xml",
        "views/augmont_api_retry_views.xml",
        # "views/customer_onboarding_views.xml",
        "views/customer_rfq_views.xml",
        "views/menu_security.xml",
        "views/purchase_order.xml",
        "views/lgd_margin_views.xml",
        "report/sale_report_inherit.xml",
        "report/augmont_tax_invoice.xml",
        'data/augmont_retry_cron.xml',
        'data/igi_config.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'contact_stage_bar/static/src/js/restrict_availability_dropdown.js',
            'contact_stage_bar/static/src/js/rename_new_button.js',
            'contact_stage_bar/static/src/js/hide_cog_menu.js',
            'contact_stage_bar/static/src/js/hide_replenish.js',
            'contact_stage_bar/static/src/css/rfq_form.css',
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3"
}
